version: '3.0'

services:
    app:
        build:
            args:
                user: ${USER}
                uid: ${UID}
            context: ./docker/php/
            dockerfile: Dockerfile
        image: laravel
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./app/:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:1.17-alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./app/:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - laravel

    db:
        image: postgres:13.3
        container_name: laravel-db
        restart: unless-stopped
        volumes:
            - ./docker/postgres/data/:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5432:5432
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
